import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Biggenning-nextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"></link> */}
      </Head>

      <main className="main-body inter ">
        <div className="main-image">
          <img
            className="w-[200px] h-[200px] rounded-full"
            src="./homeimg.jfif"
            alt="hunting cooders"
          />
        </div>
        <div className="mt-[20px] section-heading italic roboto">
          {" "}
          &lt;Hunting Coders&gt;
        </div>
        <div className="mt-[40px] w-11/12 mx-auto">
          {" "}
          <div className="capitalize primary-heading flex self-start ">Recent blogs</div>{" "}
        </div>
        <div className="blog space-y-[20px] mt-[20px]">
          <div className="blogItem card">
            <div className="section-heading">Blog post 1st Oct 2007</div>
            <div className="primary-pargraph text-justify">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur,
              inventore labore libero culpa adipisci error, minus aspernatur
              expedita cupiditate ut et corrupti. Maxime qui beatae amet
              pariatur ab asperiores repellat suscipit aperiam, culpa quam.
            </div>
            <button className="primary-button">read more</button>
          </div>
          <div className="blogItem card">
            <div className="section-heading">Blog post 12th Nov 2012</div>
            <div className="primary-pargraph text-justify">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem
              quod esse officiis amet, eveniet veniam beatae accusamus deleniti
              ea, aliquam tempora nisi, eos voluptas consectetur quisquam alias
              excepturi eius at.
            </div>
            <button className="primary-button">read more</button>
          </div>
          <div className="blogItem card">
            <div className="section-heading">Blog post 24th Jul 2022</div>
            <div className="primary-pargraph text-justify">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Aspernatur fuga, dolorem nulla consequatur, beatae officia quia
              eum aut eligendi, fugiat illum quidem sunt tempore consectetur
              error! Soluta molestias delectus ducimus veniam, nam ratione.
            </div>
            <button className="primary-button">read more</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
