// 'use client'

// import React from 'react';
// import Head from "next/head";
// import Link from "next/link";
// import styles from "../styles/Home.module.css";
// import Container from 'react-bootstrap/Container';
// import Row from 'react-bootstrap/Row';
// import Col from 'react-bootstrap/Col';
// import CreateTask from "../components/create-task"
// import { getTasksFromLocalStorage } from "../utility/utils.js"
// import { ViewTask } from "../components/view-task"

// // const currentTasks = getTasksFromLocalStorage();

// // const todoTasks = currentTasks?.length > 0 ? currentTasks.filter(task => task.status === "todo") : "No tasks found in To-DO";

// // console.log(todoTasks);

// // const inProgressTasks = currentTasks?.length > 0 ? currentTasks.filter(task => task.status === "inProgress") : "No tasks found in In Progress";

// // console.log(inProgressTasks);

// // const doneTasks = currentTasks?.length > 0 ? currentTasks.filter(task => task.status === "done") : "No tasks found in Done";

// // console.log(doneTasks);

// // const getTasksFromLocalStorage = () => {
// //   const storedTasks = localStorage?.getItem('tasks');
// //   return storedTasks ? JSON.parse(storedTasks) : [];
// // }

// // const currentTasks = getTasksFromLocalStorage();

// // console.log(currentTasks)


// export default function Home() {
//   const [storedValue, setStoredValue] = React.useState(null);

//   React.useEffect(() => {
//     const storedTasks = localStorage.getItem('tasks');
//     setStoredValue(storedTasks ? JSON.parse(storedTasks) : []);
//   }, []);

//   const todoTasks = storedValue?.length > 0 ? storedValue.filter(task => task.status === "todo") : "No tasks found in To-DO";

// console.log(todoTasks);

// const inProgressTasks = storedValue?.length > 0 ? storedValue.filter(task => task.status === "inProgress") : "No tasks found in In Progress";

// console.log(inProgressTasks);

// const doneTasks = storedValue?.length > 0 ? storedValue.filter(task => task.status === "done") : "No tasks found in Done";

// console.log(doneTasks);

// const showTodos = todoTasks && todoTasks.map((task, index) => (
//   <div key={index}>{<ViewTask title={task.title} description={task.description} />}</div>
// ))

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Ashfaq | React Assessment</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//         {/* <link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"></link> */}
//       </Head>

//       <main className="main-body inter ">
//         <div className="main-image">
//         </div>
//         <div className="mt-[20px] mb-3 flex justify-between items-center w-full">
//           <div className="section-heading italic roboto">
//             Tasks Lists
//           </div>
//           <div>
//             <CreateTask />
//           </div>
//         </div>
        
//           <Container>
//             <Row>
//               <Col>
//               <div>
//                 To-do
//               </div>
//               <div>
//               {showTodos()}
//               </div>

//               </Col>
//               <Col>In-progress</Col>
//               <Col>done</Col>
//             </Row>
//           </Container>
        
//       </main>

//       <footer className={styles.footer}></footer>
//     </div>
//   );
// }

import React, { useEffect, useState } from 'react';
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import CreateTask from "../components/create-task";
import ViewTask  from "../components/view-task";

export default function Home() {
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    const storedTasks = localStorage.getItem('tasks');
    setTasks(storedTasks ? JSON.parse(storedTasks) : []);
  }, []);

  const getFilteredTasks = (status) => {
    return tasks.filter(task => task.status === status);
  }

  const renderTasks = (taskStatus) => {
    const filteredTasks = getFilteredTasks(taskStatus);
    return filteredTasks.length > 0 
      ? filteredTasks.map((task, index) => <ViewTask key={index} title={task.title} description={task.description} />)
      : <p>No tasks found in {taskStatus}</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Ashfaq | React Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-body inter ">
        <div className="main-image"></div>
        <div className="mt-[20px] mb-3 flex justify-between items-center w-full">
          <div className="section-heading italic roboto">Tasks Lists</div>
          <CreateTask />
        </div>
        
        <Container>
          <Row>
            <Col>
              <h3>To-do</h3>
              {renderTasks("todo")}
            </Col>
            <Col>
              <h3>In-progress</h3>
              {renderTasks("inProgress")}
            </Col>
            <Col>
              <h3>Done</h3>
              {renderTasks("done")}
            </Col>
          </Row>
        </Container>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
