import React, { useEffect, useState } from 'react';
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import CreateTask from "../components/create-task";

export default function Home() {
  const [tasks, setTasks] = useState([]);
  const [editingTask, setEditingTask] = useState(null);

  useEffect(() => {
    const storedTasks = localStorage.getItem('tasks');
    setTasks(storedTasks ? JSON.parse(storedTasks) : []);
  }, []);

  const getFilteredTasks = (status) => {
    return tasks.filter(task => task.status === status);
  }

  const renderTasks = (taskStatus) => {
        const filteredTasks = getFilteredTasks(taskStatus);
        return filteredTasks.length > 0 
          ? filteredTasks.map((task, index) => (
            // <div key={index} onClick={() => setEditingTask(task)}>
            //   {editingTask && editingTask.title === task.title
            //     ? <CreateTask mode="edit" initialData={editingTask} />
            //     : (
            //       <ViewTask key={index} title={task.title} description={task.description} />
            //     )
            //   }
            // </div>
            <div key={index}>
              <CreateTask mode="edit" initialData={editingTask} />
            </div>
            
          ))
          : <p>No tasks found in {taskStatus}</p>;
      }

  return (
    <div className={styles.container}>
      <Head>
        <title>Ashfaq | React Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-body inter ">
        <div className="main-image"></div>
        <div className="mt-[20px] mb-3 flex justify-between items-center w-full">
          <div className="section-heading italic roboto">Tasks Lists</div>
          <CreateTask />
        </div>
        
        <Container>
          <Row>
            <Col>
              <h3>To-do</h3>
              {renderTasks("todo")}
            </Col>
            <Col>
              <h3>In-progress</h3>
              {renderTasks("inProgress")}
            </Col>
            <Col>
              <h3>Done</h3>
              {renderTasks("done")}
            </Col>
          </Row>
        </Container>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
